"use client";
import { useEffect, useRef, useState } from 'react';
import { ArrowRight, Box, Plus, Redo2, Undo2, Trash2, Loader2, DoorOpen, Square, Image as ImageIcon } from 'lucide-react';
import { useSceneStore, type EditorRoom } from '@/store/scene-store';
import type { SceneGraph } from '@/types/scene';
import { PlanDrawing, SampleDrawing, ROOM_COLORS } from './studio/plan-drawing';
import { requestJson } from './studio/requests';
import { sceneFromLayout } from './studio/sample';
const ROOM_TYPES=['living','bedroom','kitchen','bathroom','dining','office','corridor','balcony','yard','storage','wc'];
function NumberField({label,value,onChange,min=0}:{label:string;value:number;onChange:(v:number)=>void;min?:number}) {
 const [draft,setDraft]=useState(String(value/1000));useEffect(()=>setDraft(String(value/1000)),[value]);
 return <label className="field-label">{label}<div className="unit-field"><input type="number" step="0.05" min={min/1000} max="1000" value={draft} onChange={e=>setDraft(e.target.value)} onBlur={()=>{const n=Number(draft)*1000;if(draft.trim()&&Number.isFinite(n)&&n>=min&&n<=1000000){if(n!==value)onChange(Math.round(n));}else setDraft(String(value/1000));}} onKeyDown={e=>{if(e.key==='Enter')e.currentTarget.blur();}}/><span>m</span></div></label>;
}
export function FloorPlanEditor() {
 const s=useSceneStore(); const [error,setError]=useState('');const [notice,setNotice]=useState(''); const [zoom,setZoom]=useState(100);const request=useRef<AbortController|null>(null);
 const room=s.editorRooms.find(r=>r.id===s.selectedEditorItem);
 const door=s.editorDoors.find(d=>d.id===s.selectedEditorItem);const win=s.editorWindows.find(w=>w.id===s.selectedEditorItem);const opening=door||win;
 useEffect(()=>()=>request.current?.abort(),[]);
 const area=s.editorRooms.reduce((total,r)=>total+r.width_mm*r.height_mm/1e6,0);
 async function generate() {
  if(!s.editorRooms.length)return;
  setError('');setNotice('');
  if(s.sourceKind==='sample'){s.setScene(sceneFromLayout(s.editorRooms,s.editorDoors,s.editorWindows,'Sample apartment'));return;}
  const controller=new AbortController();request.current=controller;s.setProcessing(true,'Creating your 3D space');
  const timer=setTimeout(()=>controller.abort('timeout'),120000);
  const orientation=(rotation:number)=>rotation%180===90?'vertical':'horizontal';
  const body={rooms:s.editorRooms,doors:s.editorDoors.map(d=>({...d,orientation:orientation(d.rotation)})),windows:s.editorWindows.map(w=>({...w,orientation:orientation(w.rotation)})),overall_width_mm:Math.max(...s.editorRooms.map(r=>r.x_mm+r.width_mm)),overall_height_mm:Math.max(...s.editorRooms.map(r=>r.y_mm+r.height_mm)),source_file:s.projectName};
  try { const result=await requestJson<{scene:SceneGraph}>('/api/generate-3d',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body),signal:controller.signal});
   if(controller.signal.aborted)return;if(!result.scene?.rooms?.length)throw new Error('No usable 3D layout was returned. Your corrections are safe; please retry.');s.setScene(result.scene);
  } catch(e){if(controller.signal.reason==='timeout')setError('The request timed out. Your corrections and previous 3D result are unchanged. Try again.');else if(!controller.signal.aborted)setError(e instanceof Error?e.message:'Could not create the 3D space. Please retry.');}
  finally{clearTimeout(timer);if(request.current===controller){request.current=null;useSceneStore.getState().setProcessing(false);}}
 }
 function cancel(){request.current?.abort();request.current=null;s.setProcessing(false);setNotice('Request cancelled. All corrections and your previous 3D result are unchanged.');}
 function addRoom(){const r:EditorRoom={id:`room_${crypto.randomUUID()}`,name:'New room',type:'living',x_mm:Math.max(0,...s.editorRooms.map(r=>r.x_mm+r.width_mm)),y_mm:0,width_mm:3000,height_mm:3000};s.setEditorRooms([...s.editorRooms,r]);s.selectEditorItem(r.id);}
 function addOpening(kind:'door'|'window'){const r=room||s.editorRooms[0];if(!r)return;const item={id:`${kind}_${crypto.randomUUID()}`,x_mm:r.x_mm+r.width_mm/2,y_mm:r.y_mm,width_mm:kind==='door'?850:1200,rotation:0};if(kind==='door')s.addEditorDoor({...item,type:'hinged'});else s.addEditorWindow(item);s.selectEditorItem(item.id);}
 const updateOpening=(updates:Record<string,number>)=>{if(door)s.updateEditorDoor(door.id,updates);else if(win)s.updateEditorWindow(win.id,updates);};
 return <div className="editor-shell">
  <div className="editor-actionbar"><div><span className="eyebrow">REVIEW & REFINE</span><h1>First, get the plan right.</h1><p>Compare the source, select a room, and correct its dimensions.</p></div><div className="action-group"><button className="icon-button" aria-label="Undo correction" disabled={!s.past.length||s.isProcessing} onClick={s.undo}><Undo2 size={17}/></button><button className="icon-button" aria-label="Redo correction" disabled={!s.future.length||s.isProcessing} onClick={s.redo}><Redo2 size={17}/></button><button className="primary-button" onClick={()=>void generate()} disabled={!s.editorRooms.length||s.isProcessing}><Box size={16}/>{s.isProcessing?'Creating space…':error?'Retry 3D creation':'Create 3D space'}<ArrowRight size={16}/></button></div></div>
  {(s.isProcessing||error||notice)&&<div className={error?'editor-message inline-error':'editor-message inline-notice'} role={error?'alert':'status'}>{s.isProcessing?<><Loader2 size={17} className="spin"/><span>Waiting for your 3D space. Your layout remains saved.</span><button className="text-button" onClick={cancel}>Cancel request</button></>:error||notice}</div>}
  <div className="review-workspace">
   <div className="review-canvases">
    <section className="source-pane"><div className="pane-heading"><span><ImageIcon size={15}/>{s.sourceKind==='sample'?'Sample reference':'Your source plan'}</span>{s.extraction?.image_base64&&<label className="zoom-control">Zoom <input aria-label="Source image zoom" type="range" min="100" max="300" step="25" value={zoom} onChange={e=>setZoom(Number(e.target.value))}/></label>}</div><div className="source-image-scroll">{s.extraction?.image_base64?<div style={{width:`${zoom}%`}}><img src={`data:${s.extraction.image_mime};base64,${s.extraction.image_base64}`} alt="Original uploaded floor plan — compare all dimensions and room boundaries"/></div>:s.sourceKind==='sample'?<SampleDrawing/>:<div className="empty-source">No source preview was returned. Refer to your original file when correcting the layout.</div>}</div><div className="pane-footnote">{s.sourceKind==='sample'?'Original sample layout · not an uploaded plan':'Original image · unchanged by your edits'}</div></section>
    <section className="layout-pane"><div className="pane-heading"><span><Square size={15}/>Editable layout</span><span>{s.editorRooms.length} rooms · {area.toFixed(1)} m²</span></div><div className="layout-drawing">{s.editorRooms.length?<PlanDrawing rooms={s.editorRooms} doors={s.editorDoors} windows={s.editorWindows} selectedId={s.selectedEditorItem} onSelect={id=>s.selectEditorItem(id)}/>:<div className="empty-source"><h2>No rooms were inferred.</h2><p>Your source is still here. Add rooms manually or try a clearer plan.</p><button className="secondary-button" onClick={addRoom}><Plus size={16}/>Add first room</button></div>}</div><div className="pane-footnote"><span className="legend-dot"/>Rooms <span className="legend-line door"/>Doors <span className="legend-line window"/>Windows</div></section>
    {!!s.extraction?.warnings?.length&&<details className="fidelity-note"><summary>Notes to check against your plan ({s.extraction.warnings.filter(w=>!w.startsWith("No separate OCR")).length})</summary><ul>{s.extraction.warnings.filter(w=>!w.startsWith("No separate OCR")).map((w,i)=><li key={i}>{w}</li>)}</ul></details>}
    <div className="fidelity-note">A reviewable approximation, not a measured survey. Rooms use rectangular boundaries; check scale, openings and any angled or irregular spaces against your source before relying on the 3D view.</div>
   </div>
   <aside className="inspect-panel"><fieldset disabled={s.isProcessing}><div className="inspector-heading"><span className="eyebrow">INSPECT</span><span className="status-pill">Metres</span></div>
    <div className="room-list" aria-label="Rooms">{s.editorRooms.map(r=><button key={r.id} className={`room-list-item ${room?.id===r.id?'selected':''}`} onClick={()=>s.selectEditorItem(r.id)}><i style={{background:ROOM_COLORS[r.type]||'#e3ded3'}}/><span>{r.name}</span><small>{(r.width_mm*r.height_mm/1e6).toFixed(1)} m²</small></button>)}</div>
    <div className="inspector-add"><button className="text-button" onClick={addRoom}><Plus size={15}/>Room</button><button className="text-button" disabled={!s.editorRooms.length} onClick={()=>addOpening('door')}><DoorOpen size={14}/>Door</button><button className="text-button" disabled={!s.editorRooms.length} onClick={()=>addOpening('window')}><Square size={14}/>Window</button></div>
    {room?<div className="property-section" key={room.id}><h2>Room details</h2><label className="field-label">Name<input defaultValue={room.name} key={`${room.id}-${room.name}`} maxLength={60} onBlur={e=>{const name=e.target.value.trim();if(name&&name!==room.name)s.updateEditorRoom(room.id,{name});else e.target.value=room.name;}} onKeyDown={e=>{if(e.key==='Enter')e.currentTarget.blur();}}/></label><label className="field-label">Room type<select value={room.type} onChange={e=>s.updateEditorRoom(room.id,{type:e.target.value})}>{!ROOM_TYPES.includes(room.type)&&<option value={room.type}>{room.type}</option>}{ROOM_TYPES.map(type=><option key={type} value={type}>{type.charAt(0).toUpperCase()+type.slice(1)}</option>)}</select></label><div className="property-grid"><NumberField label="Width" value={room.width_mm} min={100} onChange={width_mm=>s.updateEditorRoom(room.id,{width_mm})}/><NumberField label="Depth" value={room.height_mm} min={100} onChange={height_mm=>s.updateEditorRoom(room.id,{height_mm})}/><NumberField label="Position X" value={room.x_mm} onChange={x_mm=>s.updateEditorRoom(room.id,{x_mm})}/><NumberField label="Position Y" value={room.y_mm} onChange={y_mm=>s.updateEditorRoom(room.id,{y_mm})}/></div><p className="input-hint">Edits apply when you leave a field. Positions are measured from the top-left.</p><button className="text-button danger" onClick={()=>{s.removeEditorRoom(room.id);s.selectEditorItem(null);}}><Trash2 size={14}/>Remove room</button></div>:opening?<div className="property-section"><h2>{door?'Door':'Window'} details</h2><div className="property-grid"><NumberField label="Width" min={100} value={opening.width_mm} onChange={width_mm=>updateOpening({width_mm})}/><NumberField label="Position X" value={opening.x_mm} onChange={x_mm=>updateOpening({x_mm})}/><NumberField label="Position Y" value={opening.y_mm} onChange={y_mm=>updateOpening({y_mm})}/></div><label className="field-label">Wall direction<select value={opening.rotation} onChange={e=>updateOpening({rotation:Number(e.target.value)})}><option value={0}>Horizontal</option><option value={90}>Vertical</option></select></label><button className="text-button danger" onClick={()=>{if(door)s.removeEditorDoor(door.id);else if(win)s.removeEditorWindow(win.id);s.selectEditorItem(null);}}><Trash2 size={14}/>Remove {door?'door':'window'}</button></div>:<div className="inspector-placeholder"><Square size={25} strokeWidth={1}/><h2>Every detail matters.</h2><p>Select a room on the plan or in the list to adjust its name, purpose and dimensions.</p></div>}
    {!!(s.editorDoors.length+s.editorWindows.length)&&<details className="opening-list"><summary>Doors & windows ({s.editorDoors.length+s.editorWindows.length})</summary>{[...s.editorDoors,...s.editorWindows].map((o,i)=><button key={o.id} className="room-list-item" onClick={()=>s.selectEditorItem(o.id)}>{i<s.editorDoors.length?'Door':'Window'} {i<s.editorDoors.length?i+1:i-s.editorDoors.length+1}<small>{(o.width_mm/1000).toFixed(2)} m</small></button>)}</details>}
   </fieldset></aside>
  </div>
 </div>;
}
