"use client";
import { useEffect, useRef, useState } from 'react';
import { Armchair, BedDouble, Lamp, Leaf, Plus, RotateCcw, RotateCw, Sofa, Trash2, Undo2, Redo2, X, SlidersHorizontal, Download } from 'lucide-react';
import { useSceneStore } from '../store/scene-store';
import { useDesignStore } from '../store/design-store';
import { catalog, type ItemKind } from '../lib/interior-design';
import styles from './interior-panel.module.css';
const colors=['#d3c4b1','#e9e3d6','#b58461','#8e9b83','#48554e','#a5784e','#676965','#303733'];
const walls=['#f2ede4','#ded6c8','#bdc5b2','#bac4c7','#cbaf98','#72796b'];
const floors=[['wood_light','Natural oak'],['wood_dark','Smoked oak'],['tile_white','Ivory tile'],['concrete','Warm concrete']];
function Icon({kind}:{kind:ItemKind}){if(kind==='bed')return <BedDouble/>;if(kind==='sofa')return <Sofa/>;if(kind==='plant')return <Leaf/>;if(kind==='floor-lamp')return <Lamp/>;return <Armchair/>;}
export function InteriorPanel(){
 const scene=useSceneStore(s=>s.scene),selectedRoom=useSceneStore(s=>s.selectedRoom),selectRoom=useSceneStore(s=>s.selectRoom);
 const design=useDesignStore();const [tab,setTab]=useState<'furnish'|'finishes'>('furnish');const [category,setCategory]=useState('All');const [notice,setNotice]=useState('');const file=useRef<HTMLInputElement>(null);
 useEffect(()=>{if(scene){design.initialize(scene);if(window.innerWidth<=620)design.setPanel(false);}},[scene]);
 if(!scene)return null;const room=scene.rooms.find(r=>r.id===selectedRoom)||scene.rooms[0];if(!room)return null;
 const selected=design.items.find(i=>i.id===design.selected),itemRoom=scene.rooms.find(r=>r.id===selected?.roomId)||room;
 const update=(patch:Parameters<typeof design.update>[1])=>{if(!selected)return;setNotice(design.update(selected.id,patch,itemRoom)?'':'That position does not fit inside the room.');};
 const save=()=>{const blob=new Blob([JSON.stringify({items:design.items,finishes:design.finishes},null,2)],{type:'application/json'});const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='spatialviz-furnishings.json';a.click();URL.revokeObjectURL(url);};
 if(!design.panelOpen)return <button className={styles.open} onClick={()=>design.setPanel(true)}><SlidersHorizontal size={17}/> Design room</button>;
 return <aside className={styles.panel} aria-label='Interior designer'>
 <header className={styles.heading}><div><span className={styles.eyebrow}>MAKE IT YOURS</span><h2>Interior studio</h2></div><button aria-label='Close interior designer' onClick={()=>design.setPanel(false)}><X size={18}/></button></header>
 <label className={styles.room}>Designing<select aria-label='Design room' value={room.id} onChange={e=>{selectRoom(e.target.value);design.select(null);}}>{scene.rooms.map(r=><option value={r.id} key={r.id}>{r.label}</option>)}</select></label>
 <button className={styles.focus} onClick={()=>{useSceneStore.getState().setViewMode("orbit");window.dispatchEvent(new CustomEvent("spatialviz:focus-room",{detail:room.id}));if(window.innerWidth<=620)design.setPanel(false);}}>Focus on this room ↗</button>
 <div className={styles.tabs}><button aria-pressed={tab==='furnish'} onClick={()=>setTab('furnish')}>Furniture & decor</button><button aria-pressed={tab==='finishes'} onClick={()=>setTab('finishes')}>Finishes</button></div>
 <div className={styles.scroll}>
 <section aria-label="Singapore home styles"><h3>Made for Singapore</h3><div className={styles.row}>{(['hdb','condo'] as const).map(style=><button key={style} onClick={()=>{if(!window.confirm(`Apply the ${style==='hdb'?'HDB warm':'Condo contemporary'} design? This replaces furniture and finishes, not your floor plan. Undo restores your current design.`))return;design.applySingaporeStyle(scene,style);setNotice(`${style==='hdb'?'HDB warm':'Condo contemporary'} applied. Fittings are design suggestions; your floor plan is unchanged.`);}}>{style==='hdb'?'HDB warm':'Condo contemporary'}</button>)}</div><p className={styles.hint}>Local carpentry, cooling and service-yard details. Editable, with Undo. These are renovation ideas—not inferred fittings.</p></section>
 {tab==='finishes'?<section><h3>Floor finish</h3><div className={styles.finishes}>{floors.map(([value,label])=><button key={value} aria-pressed={(design.finishes[room.id]?.floor||room.floor_material)===value} onClick={()=>design.finish(room.id,{floor:value,wall:design.finishes[room.id]?.wall||room.wall_color})}><span className={`${styles.material} ${styles[value]}`}/>{label}</button>)}</div><h3>Wall paint</h3><div className={styles.swatches}>{walls.map(color=><button key={color} aria-label={`Wall paint ${color}`} style={{background:color}} aria-pressed={(design.finishes[room.id]?.wall||room.wall_color)===color} onClick={()=>design.finish(room.id,{wall:color,floor:design.finishes[room.id]?.floor||room.floor_material})}/>)}</div><label className={styles.colorLabel}>Custom wall colour<input aria-label='Custom wall colour' type='color' value={design.finishes[room.id]?.wall||room.wall_color} onChange={e=>design.finish(room.id,{wall:e.target.value})}/></label><p className={styles.hint}>Finishes apply to this room. Your layout stays unchanged.</p></section>:<>
 {room.type==='bedroom'&&<section><button className={styles.focus} onClick={()=>{if(!window.confirm(`Replace furniture in ${room.label} with a suggested bedroom arrangement? Other rooms and finishes stay unchanged. You can Undo this.`))return;setNotice(design.arrangeRoom(room.id,scene)?'Bedroom arranged. Review clearances; Undo restores your previous design.':'No bed arrangement fits this room. Your design is unchanged.');}}>Arrange bedroom</button><p className={styles.hint}>A coordinated bed, bedside table and storage layout. Replaces only this room’s furniture, with Undo.</p></section>}
 {selected&&<section className={styles.selected} aria-label='Selected furnishing'><div className={styles.row}><h3>{catalog.find(c=>c.kind===selected.kind)?.name}</h3><button aria-label='Delete furnishing' onClick={()=>design.remove(selected.id)}><Trash2 size={16}/></button></div><p className={styles.hint}>Select in 3D, then drag to move. Or use precise controls below.</p><div className={styles.numeric}><label>X (m)<input aria-label='Furniture X position' type='number' step='.1' value={Math.round(selected.x*100)/100} onChange={e=>update({x:Number(e.target.value)})}/></label><label>Y (m)<input aria-label='Furniture Y position' type='number' step='.1' value={Math.round(selected.z*100)/100} onChange={e=>update({z:Number(e.target.value)})}/></label></div><div className={styles.row}><button onClick={()=>update({rotation:(selected.rotation+315)%360})} aria-label='Rotate furnishing left'><RotateCcw size={16}/>45°</button><span>{selected.rotation}°</span><button onClick={()=>update({rotation:(selected.rotation+45)%360})} aria-label='Rotate furnishing right'><RotateCw size={16}/>45°</button></div><label className={styles.scale}>Size <input aria-label='Furniture size' type='range' min='.5' max='2' step='.05' value={selected.scale} onChange={e=>update({scale:Number(e.target.value)})}/><span>{Math.round(selected.scale*100)}%</span></label><div className={styles.swatches}>{colors.map(color=><button key={color} aria-label={`Furniture colour ${color}`} style={{background:color}} aria-pressed={selected.color===color} onClick={()=>update({color})}/>)}</div></section>}
 <div className={styles.categories}>{['All','Singapore','Living','Bedroom','Kitchen','Bathroom','Decor'].map(c=><button key={c} aria-pressed={category===c} onClick={()=>setCategory(c)}>{c}</button>)}</div>
 <div className={styles.catalog}>{catalog.filter(c=>category==='All'||c.category===category).map(spec=><button key={spec.kind} aria-label={`Add ${spec.name}`} onClick={()=>{setNotice(design.add(spec.kind,room,scene)?`${spec.name} added to ${room.label}.`:'Not enough clear floor space. Choose another room or move an existing piece.');}}><span className={styles.thumb}><Icon kind={spec.kind}/><Plus className={styles.plus} size={13}/></span><strong>{spec.name}</strong><small>{spec.width} × {spec.depth} m</small></button>)}</div>
 <p className={styles.hint}>Furniture is a design suggestion, not extracted from the plan. Check door swings and walking clearances before purchasing.</p>
 </>}
 </div>
 <div className={styles.notice} role='status'>{notice}</div>
 <footer><div className={styles.row}><button disabled={!design.past.length} onClick={design.undo} aria-label='Undo interior change'><Undo2 size={16}/>Undo</button><button disabled={!design.future.length} onClick={design.redo} aria-label='Redo interior change'><Redo2 size={16}/>Redo</button><button onClick={save} aria-label='Save furnishings'><Download size={16}/>Save</button></div><div className={styles.row}><small>Saved on this device</small><button className={styles.link} onClick={()=>file.current?.click()}>Import furnishings</button></div><input ref={file} hidden type='file' accept='.json' onChange={async e=>{const f=e.target.files?.[0];if(!f)return;try{if(f.size>1024*1024)throw Error();setNotice(design.load(JSON.parse(await f.text()),scene)?'Furnishings restored.':'This file does not match the current rooms.');}catch{setNotice('Could not read that furnishings file.');}e.target.value='';}}/></footer>
 </aside>;
}
